// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBjvD8fIbeeZQHdwT3Kr8szKgKyPw6moA',
    appId: '1:360445790626:web:bc0d7d2c5aeba5d775cafb',
    messagingSenderId: '360445790626',
    projectId: 'moments-for-mom',
    authDomain: 'moments-for-mom.firebaseapp.com',
    storageBucket: 'moments-for-mom.firebasestorage.app',
    measurementId: 'G-5YRLEPQ6WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Hi76X6hsXJjS-AbhcgW0e32tO_i_0qI',
    appId: '1:360445790626:android:fee76d8ee291dfe175cafb',
    messagingSenderId: '360445790626',
    projectId: 'moments-for-mom',
    storageBucket: 'moments-for-mom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpMZ8GoyqfMXnqnWjKbOf9C6BpTOX7fCU',
    appId: '1:360445790626:ios:c6a2c479ba9260b875cafb',
    messagingSenderId: '360445790626',
    projectId: 'moments-for-mom',
    storageBucket: 'moments-for-mom.firebasestorage.app',
    iosClientId: '360445790626-6k5qvotqevpbdkfvh6q3jepk9d8f2d72.apps.googleusercontent.com',
    iosBundleId: 'com.example.mothersDay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpMZ8GoyqfMXnqnWjKbOf9C6BpTOX7fCU',
    appId: '1:360445790626:ios:c6a2c479ba9260b875cafb',
    messagingSenderId: '360445790626',
    projectId: 'moments-for-mom',
    storageBucket: 'moments-for-mom.firebasestorage.app',
    iosClientId: '360445790626-6k5qvotqevpbdkfvh6q3jepk9d8f2d72.apps.googleusercontent.com',
    iosBundleId: 'com.example.mothersDay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBjvD8fIbeeZQHdwT3Kr8szKgKyPw6moA',
    appId: '1:360445790626:web:824d5b9042910d7e75cafb',
    messagingSenderId: '360445790626',
    projectId: 'moments-for-mom',
    authDomain: 'moments-for-mom.firebaseapp.com',
    storageBucket: 'moments-for-mom.firebasestorage.app',
    measurementId: 'G-R5QGHNCZPJ',
  );
}
